version: '3.7'

services:
  web:
    build:
      context: .
    working_dir: /app
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - bundle_cache:/bundle_cache
    environment:
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache

  bundle_cache:
    image: busybox
    volumes:
      - bundle_cache:/bundle_cache

volumes:
  bundle_cache:
